{% set version = "0.9-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ipred
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ipred_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ipred/ipred_{{ version }}.tar.gz
  sha256: c3a8fb1c0c3698649768d5e93b2bb8ec6235a7efe6038cfe92e1c043b6682c5d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-class
    - r-nnet
    - r-prodlim
    - r-rpart >=3.1_8
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-class
    - r-nnet
    - r-prodlim
    - r-rpart >=3.1_8
    - r-survival

test:
  commands:
    - $R -e "library('ipred')"           # [not win]
    - "\"%R%\" -e \"library('ipred')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ipred
  license: GPL-2.0-or-later
  summary: 'Improved predictive models by indirect classification and bagging for classification, regression and survival problems  as well as resampling based estimators of prediction error. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ipred
# Title: Improved Predictors
# Version: 0.9-9
# Date: 2019-04-29
# Authors@R: c(person("Andrea", "Peters", role = "aut"), person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"), person("Brian D.", "Ripley", role = "ctb"), person("Terry", "Therneau", role = "ctb"),  person("Beth", "Atkinson", role = "ctb"))
# Description: Improved predictive models by indirect classification and bagging for classification, regression and survival problems  as well as resampling based estimators of prediction error.
# Depends: R (>= 2.10)
# Imports: rpart (>= 3.1-8), MASS, survival, nnet, class, prodlim
# Suggests: mvtnorm, mlbench, TH.data
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-04-28 16:17:41 UTC; hothorn
# Author: Andrea Peters [aut], Torsten Hothorn [aut, cre], Brian D. Ripley [ctb], Terry Therneau [ctb], Beth Atkinson [ctb]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-04-28 17:40:12 UTC
