appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jghzlYZMnhklbRu8g+VSlnCo7ITYHKd713dSBkZrb02do1E1uTZxwZtIx5GeRxVQ4EyVxle5j8ZnMI/lBgAPy4ZneyT5BRsIM1RngfRKzPDliwLdZRXRtE4XTDyef9pvQm7Fjf3fqW3XAflMelb40jMMWjEuVlzdAx4kobXNZDBc8BJXEoA7Je+dN+g7neYBy6vuG7By787nfSypfOKuzT7zTIuFmnotgcl8MFzHMpPMQ73aWJU4b7OiE3sMN1xyo7RXxns4PVoiY7KyU/aaUaq5DJFdJtogg222VtRptwXMddtOFOMZE8p/yCt5n7SC9PXY0ZrAqrQxctFi3pmiKrt8w+eTz5/I/XSrIVyh+vxC5KPAvyK8nHmLgNk41h/HXRFdzg9GEDW9/r9wATvFou/7ov6yxLps2B89VdNBrBTTwaKmuTZHVkU/yAqWL+uDf2YGrfocH6kCiSoFuGPPMfBGTrJLcaFGNVGwQExgJMM4vI+T4ygyPsY1ZbDouURK05kjdyiaumcRd34NDBLjMxKdTwK+qDOJNZjs0gZ2W0dSKSdzzOTNRVLFdpTgjhPaVzULItVx2q49UemCmOvdNUO9JGN12V6YErA0ZNY2DaoeKNSIN50xDRg3KgMORvooLUlAEsX+9InuRuAV4wBMi3zPd9bUzV3/AkeFfV11osY=
